apiVersion: v1
appVersion: "0.4.0"
description: Podinfo Helm chart for Kubernetes
name: podinfo
version: 0.2.1
home: https://github.com/petergledhill/k8s-podinfo
sources:
- https://github.com/petergledhill/k8s-podinfo
maintainers:
  - name: petergledhill
    email: petergledhill@users.noreply.github.com
engine: gotpl
